### ISSUE TITLE
Applying filter on other visualisations of the dashboard when clicked on any value on the vega visualisation

### ISSUE THREAD

**Issue by sainath-reancloud** [nyurik/kibana-vega-vis#13]
Hello Team,

This plugin solves most of our complex use-cases and it's indeed very useful. Is there a way where we could apply filter on other visualisations of the dashboard, whenever we click on a particular value on the vega visualisation. Similarly where it could emulate the 'filtering by value' provided by out of the box kibana visualisations.

**Comment by spalger** [comment]
The filters are accessible to the vis type, but I'm not confident that there is a way for vega visualizations to automatically set filters based on clicks. Perhaps we could come up with a way to define the filter desired?

@sainath-reancloud can you share the visualization you are building, the item you would like to click, and the filter you would expect to produce? Screenshots would be helpful along with sample data if you can provide it.

Thanks for the request :)

**Comment by nyurik** [comment]
@sainath-reancloud that's an awesome idea, thanks!  It should be possible to do with Vega signals - they can be modified by both the environment and by the Vega JSON. I already use it for the underlying map synchronization - a graph is notified when user moves the map (latitude/longitude/zoom signals), and the graph can position the map to a different location on some event by modifying those signals.

@spalger What's the best way for my code to set Kibana dashboardContext's filter string and fire a global update?

Note: Until #11 is fixed, there will be a full graph regeneration/reinitialization whenever the filter expression is changed, so this might cause some visual disruptions, depending on the graph.

**Comment by nyurik** [comment]
I started the implementation in https://github.com/nyurik/kibana-vega-vis/compare/indexPattern but the `indexPattern` I get from the code injector has index `id` set to `undefined`.  @nreese do yuo know how to properly get the index ID and the context filter string, and also to modify them from code?

**Comment by nreese** [comment]
The [indexPatterns get](https://github.com/elastic/kibana/blob/5.5/src/ui/public/index_patterns/index_patterns.js#L19) method creates a new index pattern when an id argument is not provided.

What are you trying to do? Are you trying to create a new index-pattern or get an existing index-pattern based on the index-pattern title?

**Comment by spalger** [comment]
@nyurik I'm not super familiar with this section of things and I assume it's changing a fair amount with the work that @lukasolson and @Bargs have been doing. It looks like you're going to want to checkout the following modules:

 - [filterBarClickHandler](https://github.com/elastic/kibana/blob/013b7943dc8358f29c6e52dbefad02b9cefe8fc6/src/ui/public/filter_bar/filter_bar_click_handler.js) used to listen to click events from Kibana visualizations and create filters based on the queries used by that visualization
 - [queryFilter service](https://github.com/elastic/kibana/blob/013b7943dc8358f29c6e52dbefad02b9cefe8fc6/src/ui/public/filter_bar/query_filter.js) this seems to manage the state of the query box at the top of the page, but I'm not certain
 - [filterManager service](https://github.com/elastic/kibana/blob/013b7943dc8358f29c6e52dbefad02b9cefe8fc6/src/ui/public/filter_manager/filter_manager.js) another peice to the puzzel, but I'm not certain how it ties in

**Comment by nyurik** [comment]
Thanks @spalger. @nreese has sent me some good links too, documenting here for others:

> Here is an example of how a map kibana plugin I wrote added geospatical filter pills. Line 7 is an example of how to get an instance of the interface. Line 63 is an example of how to add a new filter. Your code could do the same. When the signal is passed to your visualization, your code can convert that into a filter and add it to kibana. https://github.com/nreese/enhanced_tilemap/blob/master/public/vislib/geoFilter.js#L7
> The rest of the code is looking for any filters previously built so that they can be updated instead of making a new filter each time

**Comment by robinsummerhill** [comment]
Just adding a link to a tutorial that shows how to use the `filterManager` service to add a filter to the dashboard: https://www.timroes.de/2015/12/06/writing-kibana-4-plugins-visualizations-using-data/#adding-filters-on-click

**Comment by thekofimensah** [comment]
Yes, needed! That would take the vega visuals to the next level :)

**Comment by nyurik** [comment]
Update:   Per @timroes , there is currently some refactoring going on inside Kibana to make accessing filters easier.  I am waiting for that work to complete, and once done, I will add this feature.  Essentially I need two functions from Kibana:  `getContextFilterAsString()`  and  `setContextFilterStringAndUpdateScreen(newFilter)`.  Once these two functions are ready, it should be fairly easy to add them to the Vega plugin.

**Comment by nyurik** [comment]
This issue was moved to elastic/kibana#17210
