### ISSUE TITLE
How to work with two aggregations

### ISSUE THREAD

**Issue by IIIEII** [nyurik/kibana-vega-vis#16]
Hi guys!
Could you help me understand how to work with elasticsearch data?
I'm trying to build binned scatterplot on data from elasticsearch.
I'm gonna use days for X axis and category field for Y axis.
To query data I use two aggregations like so:
```
          "aggs": {
            "categories": {
              "terms": {
                "field": "category.keyword"
              },
              "aggs": {
                "hist": {
                  "date_histogram": {
                    "field": "@timestamp",
                    "interval": "24h",
                    "time_zone": "Europe/Moscow",
                    "min_doc_count": 1
                  }
                }
              }
            }
          }
```
And data returned are grouped:
```
[
  {
    "key": "category 1",
    "buckets": [
      {
         "key": "date1",
         "doc_count": 10
      },
      {
         "key": "date2",
         "doc_count": 10
      }
    ]
  },
  {
    "key": "category 2",
    "buckets": [
      {
         "key": "date1",
         "doc_count": 10
      },
      {
         "key": "date2",
         "doc_count": 10
      }
    ]
  }
]
```
Every example of vega visualisations uses flattened data. Are there any ways to use such grouped data here?

**Comment by nyurik** [comment]
This [example](https://github.com/nyurik/kibana-vega-vis/blob/master/examples/logstash/logstash-geosrc-map-with-destinations.hjson#L142) uses double-aggregates. It uses a "group" mark, which takes data from `logCount`, gives it a new name `selectedDatum`. The marks inside the group work with each individual value (level 1).   The next level is the same thing - again, uses "group" mark (level 2).  Good luck!  P.S.  Please file this on stackoverflow - this way there are high chances someone from Vega team will provide additional insights.
