### ISSUE TITLE
Querying Elastic Search example

### ISSUE THREAD

**Issue by chintanrp** [nyurik/kibana-vega-vis#17]
I'm trying to create some visualization on Kibana plugin of vega but not able to so with elastic search query example provided. Can you please provide some more example with elastic search query on different vega visualization?

**Comment by nyurik** [comment]
@chintan-29 what query are you using?  Do you have the data in your elasticsearch?  Have you set the time filter range in the upper right corner?

**Comment by chintanrp** [comment]
Yes, I' have data in elasticsearch and time filter is perfectly set. I can create line chart and bar chart as per your examples but geo-map is not loading data always gives error "Loading failed". One question is- do this plugin require internet connection to load anything? because my server don't have that. If yes then is there any alternate way? Also I want to create some complex examples like airport connections/scattered plots..

**Comment by nyurik** [comment]
[geo-map](https://github.com/nyurik/kibana-vega-vis/blob/master/examples/logstash/logstash-geosrc-map.json) uses Elastic map service, so unless you have an alternative tile server inside your organization, you won't be able to see the map.  Also, [it uses a data layer](https://github.com/nyurik/kibana-vega-vis/blob/master/examples/logstash/logstash-geosrc-map.json#L31) from Elastic geo service - the outline of each country. You can change that URL to a local one and upload the data there.

BTW, if you want, you can disable the underlying map by setting `"mapStyle": false` in the `_hostConfig` section. Won't look as good of course :)

**Comment by chintanrp** [comment]
I did only below changes on your example to check
 "name": "logCount",
      "url": {
        "**index": "flat_edcr_v7",**
        "%context_query%": "start",
        "body": {
          "size": 0,
          "aggs": {
            "countries": {
              **"terms": {"field": "coordinates", "size": 200}**
            }
          }
        }
      },

But it loading geo-map without data and giving error message that "Loading failed". DO you have any ides on this? Also is there any way we can check error logs(detailed)?
![image](https://user-images.githubusercontent.com/7401809/30993534-0d7b0f56-a475-11e7-94ff-6d6eca96f71e.png)

**Comment by nyurik** [comment]
@chintan-29 the rendering happens on the client side, so it doesn't matter if server has access -- as long as the browser can get both data sources, it should be fine. 

Second thing - please double check that you have the latest Vega plugin version.

Can you get to https://layers.geo.elastic.co/blob/5659313586569216?elastic_tile_service_tos=agree from your browser?

Open browser debugger (F12), and slightly modify the graph (e.g. add an extra space somewhere) -- and see what network requests it makes.  With [this graph](https://github.com/nyurik/kibana-vega-vis/blob/master/examples/logstash/logstash-geosrc-map.json), I see two:  the URL above, and a call to _search.  Do you see both? Do both return valid data?  Are there any issues in the console view?

**Comment by chintanrp** [comment]
Thanks @nyurik! You solved my confusion about rendering data.
As per your suggestion I checked and sound that URL has data on network requests but _search has errors. But after looking into this I found out that this might not be the example I was looking. 
I have one filed as coordinates, which contain both lat/long and I want to plot all those on graph as my first step. But my final goal is to create same visualization as airport connection.
If you have some more examples already created then can you please provide? Or I can reach to you if I need any help.

**Comment by nyurik** [comment]
@chintan-29 I just uploaded a new version with more debugging and better error reporting and debugging access (see readme).  I would recommend following [instructions](https://github.com/nyurik/kibana-vega-vis/tree/master/examples) to generate data, and copy/paste various examples from the folder.  The [logstash-geosrc-map-with-destinations.hjson](https://github.com/nyurik/kibana-vega-vis/blob/master/examples/logstash/logstash-geosrc-map-with-destinations.hjson) is the closest example to the airports connection example.

**Comment by chintanrp** [comment]
Thanks!
