### ISSUE TITLE
Incorrect Kibana version in plugin error

### ISSUE THREAD

**Issue by michaelkeevildown** [nyurik/kibana-vega-vis#2]
Hey,

I love the plugin! I am however running into a little issue.

```
Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [vega_vis]. Expected [5.5.1]; found [5.5.0]"
```

I have followed the instructions, so:

- Downloaded Kibana 5.5.1 from https://www.elastic.co/downloads/kibana
- Ran the following command to install Vega:
   - `./bin/kibana-plugin install https://github.com/nyurik/kibana-vega-vis/releases/download/0.1.1/vega_vis-0.1.1.zip`

And then I get the following output:

```
~/kibana-5.5.1-darwin-x86_64
>> ./bin/kibana-plugin install https://github.com/nyurik/kibana-vega-vis/releases/download/0.1.1/vega_vis-0.1.1.zip
Attempting to transfer from https://github.com/nyurik/kibana-vega-vis/releases/download/0.1.1/vega_vis-0.1.1.zip
Transferring 19867293 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [vega_vis]. Expected [5.5.1]; found [5.5.0]"
```

To my understanding, I am running 5.5.1 as that is the latest major version from Elastic. Any help would be greatly appreciated!

**Comment by nyurik** [comment]
@michaelkeevildown I posted both 550 and 551 versions - https://github.com/nyurik/kibana-vega-vis/releases/tag/v0.1.2  -- see if that works?

**Comment by michaelkeevildown** [comment]
thanks @nyurik that worked like a charm!
