### ISSUE TITLE
Installing Kibana-vega-vis plugin errors out.

### ISSUE THREAD

**Issue by rjonala** [nyurik/kibana-vega-vis#20]
Hi, 

I am trying to install Kibana-vega-vis plugin and it is throwing following error,

```
Plugin installation was unsuccessful due to error "Optimizations failure.

    ERROR in ./plugins/vega_vis/public/vega_vis.controller.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /usr/share/kibana/src/ui/public/resize_checker in /usr/share/kibana/plugins/vega_vis/public
     @ ./plugins/vega_vis/public/vega_vis.controller.js 16:24-52
```
Can someone please help solve this issue?

Thanks

**Comment by nyurik** [comment]
Hi, what's the exact command you use to install it? Also, what exact version of Kibana are you using?

**Comment by rjonala** [comment]
Hi,

I followed the following steps,

```
Download https://git.bitsensor.io/front-end/elastalert-kibana-plugin/builds/5251/artifacts/file/build/elastalert-0.0.6.zip
Unzip
Move unzipped elastalert dir into empty ./kibana dir
Change "version" into package.json to your version
Zip kibana dir. You should get this structure inside your zip file:
/kibana
-/elastalert
--/node_modules
--/public
--/server
--/index.js
--/package.json
then install like this:
 cd /usr/share/kibana
 ./bin/kibana-plugin install file:///tmp/elastalert.zip
```
Replaced elastalert with Kibana-vega-vis plugin and the version of Kibana I am using is 5.3.2. Also, I have edited package.json to 5.3.2 for Kibana version.

**Comment by nyurik** [comment]
@Amruth007 please try the [instructions in the README](https://github.com/nyurik/kibana-vega-vis#quick-demo)

**Comment by rjonala** [comment]
Hi Yuri,

The Ubuntu box doesn't have internet connection. So I have to first download it and install it.

**Comment by nyurik** [comment]
@Amruth007 sorry, I just noticed that you use Kibana 5.3.2. I have only tested for 5.5.* and 5.6.*, so I don't know if it would work.  The Kibana plugin API might have been substantially different.  BTW, you can use one of the releases and simply change the package.json's kibana.version there, before re-ziping and using the plugin install with file://... .   If the code is substantially different, I am not sure how much effort it would be to backport it.  CC: @nreese @spalger

**Comment by rjonala** [comment]
I am trying it on Ubuntu which has Kibana 5.3.2 for my testing purpose. If you can assure
me this plugin definitely works on Kibana 5.5.*, then I would try directly on UAT Kibana server(Redhat) which has Kibana 5.5.*

**Comment by nyurik** [comment]
Well, I haven't heard any installation issues recently, so **should** work :)   I would highly advise having the same version in all the testing stages, as internal API is rapidly transforming, and what worked in 5.3.2 might no longer work in 5.5.  Let me know how it goes :)

**Comment by rjonala** [comment]
Thanks Yuri. Can you please confirm the way I am installing(mentioned above) is correct?

**Comment by nyurik** [comment]
@Amruth007 partially. I would recommend downloading the correct file from the [releases](https://github.com/nyurik/kibana-vega-vis/releases), and installing it directly with `bin/kibana-plugin install file:///...`, without any additional steps.

**Comment by nreese** [comment]
Lots of the kibana imports changed between 5.4 and 5.5 so the plugin will not work in 5.3

**Comment by rjonala** [comment]
Hi Yuri and Nathan,

It worked with Kibana 5.5.1. But can you please mention somewhere that it only works with 5.4.* and above. Because I spent about 2 days :(

Thanks for your support. You responded very fast. :)

**Comment by nyurik** [comment]
@Amruth007 "officially" it works only with the released versions - that's why i point to them in the README. Beyond that - your milage may vary. Its fairly hard to test for all the older versions.  Good luck with the graphs!

**Comment by rjonala** [comment]
Hi Yuri,

One more question- If I want to upgrade Kibana to version 6.0.0 , do I need to reinstall vega-vis once again? How does it work in this scenario?

**Comment by nyurik** [comment]
5.6 is supported, but we are still working on 6.x support. Should be available soon.

**Comment by rjonala** [comment]
So if I have to install vega-vis 6.x, do I need to uninstall 5.x and then install vega-vis 6.x ?

**Comment by nyurik** [comment]
Yes, but vega-vis 6.x is still being worked on :)
