### ISSUE TITLE
does or will this awesomeness support kibana 5.4

### ISSUE THREAD

**Issue by xycloud** [nyurik/kibana-vega-vis#25]
does or will this awesomeness support kibana 5.4?

**Comment by nyurik** [comment]
@xycloud which version specifically?

**Comment by xycloud** [comment]
version 5.4.3

**Comment by nyurik** [comment]
@xycloud i poked at it a bit, but it seems the backport will be relatively hard. There was a lot of changes in the Kibana API, and supporting an older Kibana version when everything is actively moving towards 6.x would be fairly difficult. As always, pull requests are welcome :)

**Comment by nyurik** [comment]
I'm closing it for now, as I don't plan to work on it in a near future.  PRs are welcome :)
