### ISSUE TITLE
Support Kibana filter expression in Vega code

### ISSUE THREAD

**Issue by evanceheallyg** [nyurik/kibana-vega-vis#3]
Hello Team

Firstly, thanks for the awesome widget. This adds great flexibility in creating custom graphs with custom data sources. One clarification we have is, apart from the @timestamp : %timefilter%, is there a possibility to add dashboard context similar to transform_vis - _DASHBOARD_CONTEXT_? Currently, if we add a vega visual to an existing dashboard, the data is not filtered based on the other graphs filters. Is there any way to achieve the same?

**Comment by nyurik** [comment]
@evanceheally2 thanks for your feedback!  Yes, I do plan to add this capability shortly - need to figure out some internal API to make this work, but should be doable.

I am not yet sure if the initial index-picking screen is needed, but it seems that enabling the "filter" input field automatically shows index picking screen when creating new visualization. I will need to talk to Kibana devs to see if its possible to avoid it.

**Comment by evanceheallyg** [comment]
Thank you so much Nyurik for the update. The problem we are facing with transform_vis is that we need to write a lot of js to create a graph. This makes the widget non usable to share with clients to create runtime dashboards. Vega is great but the non availability of filter option makes that too non usable for our scenario. 
Any work arounds/ other plugins that you could point us to that could provide us vega like functionality with kibana filter expressions?

**Comment by nyurik** [comment]
@evanceheally2 - I do plan to add it shortly, stay tuned :)  If you can help with JS development, even better!

Setting `requiresSearch: true` in [vega_vis.vis_type.js](https://github.com/nyurik/kibana-vega-vis/blob/master/public/vega_vis.vis_type.js#L36) enables the search box, but I haven't yet figured out how to get the **string value** of that search box, as well as the index name. Adding it to the code afterwards should be very easy. Maybe @spalger or @nreese know?

**Comment by evanceheallyg** [comment]
I would love to help with JS development but unfortunately, I am more into data science and databases and my knowledge wrt JS is much limited. But I can point to one of our team members who can help in JS @rajeeshk... I would eventually try to start helping once I gain enough knowledge on the same.

**Comment by nyurik** [comment]
done in release v0.2.0
