### ISSUE TITLE
To support install the plugin for kibana 6.1.0

### ISSUE THREAD

**Issue by cjw0122** [nyurik/kibana-vega-vis#31]
I tried to install the plugin in my environment, but can't install the plugin for kibana 6.1.0. It's better to have this support. Thx a lot.

root@bpmtap-2:/home/software/kibana-6.1.0-linux-x86_64# bin/kibana-plugin install https://github.com/nyurik/kibana-vega-vis/releases/download/v0.5.1/vega_vis-0.5.1--for-Kibana-6.0.1.zip
Attempting to transfer from https://github.com/nyurik/kibana-vega-vis/releases/download/v0.5.1/vega_vis-0.5.1--for-Kibana-6.0.1.zip
Transferring 28444904 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [vega_vis]. Expected [6.1.0]; found [6.0.1]"

**Comment by nyurik** [comment]
It's coming. In the mean time, please describe your usecases - it is always good to understand how it is being used. thx

**Comment by cjw0122** [comment]
My use case is to show passed percentage trend by build level. Our data is all regression records of different build level on elasticsearch with field passed point and total point, I have to aggregate by build level, then sum passed point and total point by build level, then have sum passed / sum total. 
We select the latest elastic search and kibana which is 6.1.0.

I successfully show that chart using vega!Thx a lot!

**Comment by nyurik** [comment]
done https://github.com/nyurik/kibana-vega-vis/releases/tag/v1.0.0
