### ISSUE TITLE
Do we support to enable vega tooltips on kibana-vega-vis?

### ISSUE THREAD

**Issue by cjw0122** [nyurik/kibana-vega-vis#33]

**Comment by nyurik** [comment]
I have been thinking about it. I will see if it`s easy enough to do, and may enable it as an option. You could already use the [tooltip channel in VegaLite](https://vega.github.io/vega-lite/docs/tooltip.html) and tooltip property on most of the Vega [marks](https://vega.github.io/vega/docs/marks/). Would be good to know why the build-in tooltip support is not sufficient (I know Vega Editor also uses it)

**Comment by cjw0122** [comment]
That's useful for me, thx  a lot.

**Comment by nyurik** [comment]
@cjw0122 could you elaborate why the build-in tool-tip stuff is not sufficient? (see links above)

**Comment by cjw0122** [comment]
I want to show multiple fields on the tooltips, the default tooltip channel just can show 1 field.

**Comment by cjw0122** [comment]
I see for multiple fields, we can use Using Vega-tooltip plugin in above links, but I don't know how to enable that in kibana-vega-vis.

**Comment by nyurik** [comment]
This issue was moved to elastic/kibana#17215
