### ISSUE TITLE
Can not generate parentKey dynamically in stratify transformation

### ISSUE THREAD

**Issue by dimikhan** [nyurik/kibana-vega-vis#34]
I am creating a tree using stratify transformation. I dont have parentKey within my data but, I want to generate it for each record using two clauses.

parent.step_id = child.step_id-1
parent.@timestamp = immediate previous timestamp of child
I have used lookup transformation here. But it seems to me that lookup transformation does not support two clauses and also it looks for exact value, not within a matching value range. How can I achieve this?

Note: I tried a filter before lookup. But I can not filter with timestamp data. And more over I can not run filter on secondary datasource. If I use it in my primary datasource, primary datasource itself will be modified. Which I dont want.
I have also raised this issue in the vega-transforms repo - https://github.com/vega/vega-transforms/issues/4

**Comment by dimikhan** [comment]
Solution provided by Roy I - https://groups.google.com/forum/#!topic/vega-js/Q2XrYMOVluw

**Comment by nyurik** [comment]
Glad it was solved!  A new version is on its way, will be released any day now with many improvements. Closing this issue, let me know if it needs to reopen.
