### ISSUE TITLE
How to revise kibana-vega-vis

### ISSUE THREAD

**Issue by bt2414** [nyurik/kibana-vega-vis#35]
As my project request, I may need to revise the vega to fulfill some of our requirements.

I can access and revise vega source code but if I want to use your kibana plugin, I am confused about how to do any modifications.

Could you share me some tutorials for how to revise your code?

Thanks so much.

**Comment by nyurik** [comment]
@bt2414 I don't understand.  What are you trying to accomplish?

**Comment by bt2414** [comment]
Hi. Thanks so much for your reply. I want to change source code of vega(vega.js) in original vega. However, I can't find it in your viz plugin. Could you share me a way to revise your code?

**Comment by nyurik** [comment]
You mean https://github.com/vega/vega and other related github repositories?

**Comment by bt2414** [comment]
Yes. Can I change your code to do some modifications?

**Comment by nyurik** [comment]
What kind of a change would you like to make?
If the change is with the Vega itself, the best way would be to write an issue at their github page, and let the community discuss it. You can always submit a pull request with your desired change.
If the change is with the Kibana plugin, please describe what you want changed. We can discuss it and I will be happy to merge any reasonable pull requests.

**Comment by bt2414** [comment]
Hi. Thanks for you reply. I only want to do some style changes. For example, the border of treemap is white. I want to change it to be black. I don't think it is an issue of vega, but for some reason, I need to change the style of visualizations.

**Comment by nyurik** [comment]
@bt2414 which specific graph are you referring to?  When making a graph, you can decide which colors to use for everything.
