### ISSUE TITLE
Newbie issue with multi index elasticsearch

### ISSUE THREAD

**Issue by ranayayas** [nyurik/kibana-vega-vis#36]
Hi,

I would like to query two index in Elasticsearch (time series data) and show them in one graphic in Kibana-vega. I have read and try several example in https://vega.github.io/editor/ , however still have no clear idea how to do it.
Could you please give right direction that I can follow?
Thanks

**Comment by nyurik** [comment]
@ranayayas hi, please give a bit more information about the format of your data, and what exactly you are trying to show.  For example, create a github gist with the output of your ES queries (you would have two). 

Also, have you been able to change the initial example to show at least one graph the way you want it to appear? If so, you may want to try [vegalite layers](https://vega.github.io/vega-lite/docs/layer.html) to draw multiple data sources as a single graph.

In general, I would highly recommend [tutorials](https://vega.github.io/vega-lite/tutorials/getting_started.html)

**Comment by ranayayas** [comment]
Tks @nyurik . I will try to follow your direction about gist and layers
