### ISSUE TITLE
Zoomable Treemap

### ISSUE THREAD

**Issue by shankarshinde2011** [nyurik/kibana-vega-vis#37]
looking for the support for Zoomable Treemap
ex. https://bost.ocks.org/mike/treemap/

**Comment by nyurik** [comment]
@shankarshinde2011 I think it would be better to ask this in https://github.com/vega/vega or post in https://groups.google.com/forum/#!forum/vega-js - a fairly active group. In theory it should be possible, just maybe non-animated zoom.  Basically it would be a graph similar to [treemap](https://vega.github.io/vega/examples/treemap/), but it should be based on a data source that has a filtering transformation. The filter would be based on a signal. The signal should change its value on click. So whenever user clicks something, new filter expression is applied to the data, and you get a graph. The animation would be cool, but I'm not exactly sure if its possible in Vega yet (there was some attempts to do it).
