### ISSUE TITLE
Installation Problem 6.1.1 on windows 10 - Java Script out of memory

### ISSUE THREAD

**Issue by jesterle** [nyurik/kibana-vega-vis#40]
Hello.

I am trying to install the latest 6.1.1 of vega-vis on my windows 10 ELK server. 
Please see the attached screenshot for the error message. 
After I start kibana, there is no vega-icon displayed. 

![javascripterror_vega](https://user-images.githubusercontent.com/35337421/35919072-d48e8e1c-0c0b-11e8-8609-7be180b9075e.JPG)

Any help is greatly appreciated.

**Comment by nyurik** [comment]
Wow, this looks like node is running out of memory. I'm not sure if its Vega related.  Try to to download kibana 6.1.1 into a separate dir, and install the plugin there. Also check how much free RAM you have - the error seems to be coming from the underlying Node engine.

**Comment by tylersmalley** [comment]
@jesterle, do you have any additional plugins installed? Are you specifying any `NODE_OPTIONS` when running Kibana?

To increase the memory available to Kibana you can set the `max_old_space_size`

`NODE_OPTIONS="--max_old_space_size=4000" bin/kibana`

**Comment by jesterle** [comment]
Thanks for your help!

@nyurik: 
I am trying this right now, worked fine. Installed vega:
RAM: installed 32Gb, used while running the kibana-plugin: 5.8-5.7 Gb (in use) of 25.5Gb available

Server, where it failed: 
Ram: installed 32GB, 
used while running, 9Gb, available 22.8Gb
After the fatal error happened, the used memory drops to 7.9Gb


@tylersmalley 
yes, I do have additional kibana plugins installed. (which is the difference to the other server)
but kibana isn't running, during installation
plugins are:  Milestones, dotplot, network-vis

node_options?  Where do I have to check? 
in elasticsearch.yml I dont have these kind of settings.

**Comment by tylersmalley** [comment]
@jesterle, I see, this is during plugin installation. During plugin installation, we are compiling all the code, for all of the plugins. The plugins you have are bringing you over the default Node threshold. Side note: this has been [improved](https://github.com/elastic/kibana/pull/15907) in Kibana 6.2.

To combat this, you can increase the memory available to Kibana by increasing it when installing the plugin.

`NODE_OPTIONS="--max_old_space_size=4000" bin/kibana-plugin install <url>`

**Comment by nyurik** [comment]
@tylersmalley I don't think that command would work in Windows.  I think it should be

```
set NODE_OPTIONS=--max_old_space_size=4000
bin\kibana-plugin install <url>
```
(haven't tested)

**Comment by jesterle** [comment]
Thanks guys. I will try this out tomorrow. 

I got it to work, I deleted two of the other plugins. So it seems that might be the problem.

I will get back to you tomorrow. Thanks again.
