### ISSUE TITLE
Vega vis not displaying correctly

### ISSUE THREAD

**Issue by porkiz** [nyurik/kibana-vega-vis#43]
Hi I have successfully installed vega vis into kibana 6.1.1 but both the visualisations and dashboard tabs are not showing anything. 

![vega issue](https://user-images.githubusercontent.com/17869580/36519870-e84facb0-17c8-11e8-9518-e663a4b3918e.PNG)

Tested on 6.1.2 kibana and it works flawlessly but not on 6.1.1 kibana. Any help would be much appreciated.

The file used is: https://github.com/nyurik/kibana-vega-vis/releases/download/v1.1.1/vega_vis-1.1.1--for-Kibana-6.1.1.zip

**Comment by nyurik** [comment]
@porkiz thx for the report, seems like something is crashing. I will try to reproduce. Which plugin version did you install?  Please add direct link to the file. Thx!

**Comment by nyurik** [comment]
I staged the blog post, but there is currently a problem with the markdown syntax highlighting (i reported it to the support, and they are investigating).  Technically its ready to go (feel free to edit it right in the markdown area if you see bad grammar or something is unclear)

https://staging-website.elastic.co/blog/sankey-visualization-with-vega-in-kibana

**Comment by nyurik** [comment]
@porkiz I tested 6.1.1 with [ver 1.1.1](https://github.com/nyurik/kibana-vega-vis/releases/download/v1.1.1/vega_vis-1.1.1--for-Kibana-6.1.1.zip) (direct link to file), and it seems to work just fine. Please try to download a new version of Kibana & ES 6.1.1, and install the above plugin, and see if it works. If it does, its most likely an issue with your current installation.  Ping me if you get any new data. Thx!
