### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jgbarah** [nyurik/kibana-vega-vis#44]
I'm sorry if I missed it, but I couldn't find licensing information for kibana-vega-vis. Could you please include the ususal LICENSE.md (or similar) file, and/or licensing information in source code files (I checked some of them randomly, but I couldn't find any).

**Comment by nyurik** [comment]
@jgbarah thanks for the ping, it was specified inside the `package.json`. I added the LICENSE file.

**Comment by jgbarah** [comment]
Thanks!!!
