### ISSUE TITLE
How to visualize bar chart

### ISSUE THREAD

**Issue by chuski92** [nyurik/kibana-vega-vis#45]
Hello! I'm new into using Vega, but I succeeded in show a dot graph, I made it to change color and shape using one of the _source fields.
But I have problems into show a stacked bar graph.
Here is the code:

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "mark": "bar",
  "data": {
    "url": {
      "%context%": true,
      "%timefield%": "@timestamp",
      "index": "networkstat-*",
      "body": {
        "size": 10000,
        "_source": [
          "@timestamp",
          "ms",
          "status",
          "remotehost"
        ]
      }
    },
    "format": {
      "property": "hits.hits"
    }
  },
  "transform": [
    {
      "calculate": "toDate(datum._source['@timestamp'])",
      "as": "time"
    }
  ],
  "encoding": {
    "x": {
      "timeUnit": "minutes",
      "field": "time",
      "type": "temporal",
      "axis": {"title": "Minutes"}
    },
    "y": {
      "field": "_source.remotehost",
      "aggregate": "count",
      "type": "quantitative"
    },
    "color": {
      "field": "_source.remotehost",
      "type": "nominal",
      "legend": {"title": "Hosts"}
    }
  }
}
```

I want to show a stacked bar with time series in the X axis and show each host with different color.
But it raises an error: "a._source is undefined" if I change the color field with "time" it works, but not as I wanted.

**Comment by nyurik** [comment]
@chuski92, in order to stack something vertically (along the Y axis), you must have bucketed values along the x axis.  Otherwise your time might vary by a second, and bars wouldn't align one on top of the other.  Take a look at https://www.elastic.co/webinars/vega-plugin-custom-visualizations-with-kibana
