### ISSUE TITLE
%timefield% and %context% error

### ISSUE THREAD

**Issue by Herb4t-** [nyurik/kibana-vega-vis#47]
Hey,
Having a little problem when i set the two fields, can i have more informations about this error ? 
![image](https://user-images.githubusercontent.com/6637814/36903814-176ed388-1e2f-11e8-8a1c-c38e4a261d40.png)

**Comment by emilmirzayev** [comment]
Hey there,
is your timefield has "@" sign before it? Sometimes timfields in kibana are in "@timefieldname" format

**Comment by nyurik** [comment]
@Herb4t- does the graph work if you remove both %timefield% and %context% ?  What if you remove just %timefield%? If yes to both, than just like @emilmirzayev suggested, I think you gave the wrong field name for the timefield.  Double check your data structure.  Also, use browser's developer tools (usually F12 in chrome on Windows & Linux), make some change to the vega spec, and see what shows up in the networking tab - you should see the exact error that elasticsearch server returns.

**Comment by Herb4t-** [comment]
Hi, thanks for your answer, i tested to remove both %timefield% and %context% and it work, but with one of this or both, it doesn't work, i checked my data field and all is ok, so i really don't understand how those two parameters works 🤔

**Comment by nyurik** [comment]
@Herb4t- it seems Elasticsearch server is returning some unexpected error. Could you check the network tab of your [browser's debugging tools](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_are_browser_developer_tools) - it should list all network requests that failed - and paste that error here. Make sure you open dev tools before you open your vega vis, or you can also make some minor modification to the Vega code and click play.

**Comment by Herb4t-** [comment]
@nyurik 
`{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"request [/bilan_construction/_search] contains unrecognized parameters: [%context%], [%timefield%] -> did you mean [stored_fields]?"}],"type":"illegal_argument_exception","reason":"request [/bilan_construction/_search] contains unrecognized parameters: [%context%], [%timefield%] -> did you mean [stored_fields]?"},"status":400}`

Is it ok for you ?

**Comment by nyurik** [comment]
@Herb4t- this is very strange.  Both %context% and %timefield% should have been removed by the Vega plugin before being passed to the server, but that clearly is not happening.  To debug this, I think I would need a bit more info:

* I assume the error message you pasted last comes when you used Vega plugin, not from the Kibana's "dev tools" tab. Correct?
* Copy the _search request from the networking tab that generated that error - right click on the _search and click "copy / copy as curl"
* What plugin and kibana version are you using?  (ideally, link to the specific plugin release file you installed, or tell me if you are using the built-in Vega version in Kibana 6.2.x)
* When you create a new Vega graph, and you get the default vega-lite graph, does that work ok?
* Could you send me your complete Vega-lite graph specification that generates an error?  Either copy/paste the text (not image), or attach the file to this ticket.  You can also email it to me if it should remain private (YuriAstrakhan@gmail.com)
* Run these commands from the browser's development tools (console):
  * `VEGA_DEBUG.VEGA_VERSION`
  * `VEGA_DEBUG.VEGA_LITE_VERSION`

Thanks!

**Comment by Herb4t-** [comment]
here is the curl of the error (from the browser dev tool)

`curl "http://localhost:5601/elasticsearch/bilan_construction/_search?"%"25context"%"25=false&"%"25timefield"%"25="%"40timestamp" -H "Accept: application/json, text/plain, */*" --compressed -H "Accept-Language: en-US,en;q=0.5" -H "Connection: keep-alive" -H "content-type: application/json" -H "Host: localhost:5601" -H "kbn-version: 5.6.1" -H "Referer: http://localhost:5601/app/kibana" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0" --data ""`

i'm using Kibana 5.6.1, and my plugins : 
![image](https://user-images.githubusercontent.com/6637814/37397500-0fd20bbc-277c-11e8-9cb4-8ca9f8f090f7.png)
i'm on old version of kibana to use the enhanced_tilemap plugin :/ 

using this veg version : https://github.com/nyurik/kibana-vega-vis/files/1688997/vega_vis-0.5.4--for-Kibana-5.6.1.zip

and for the `VEGA_DEBUG` commands : 
![image](https://user-images.githubusercontent.com/6637814/37398492-ffbf525e-277e-11e8-9a54-b21ed7febfca.png)

**Comment by nyurik** [comment]
Aha, I think I know what's going on.  The very old Kibana version was using a different context param passing, that was later changed. You are using the newer one, but it might be that the older pattern is required.  See https://github.com/nyurik/kibana-vega-vis/releases/tag/v1.0.0 notes.  Try replacing both %context% and %timefield% with just    `"%context_query%": "date_depot"`

**Comment by Herb4t-** [comment]
Ah my bad, ok, your solution work, i'll try to update to a newer version, thank you very much :)

**Comment by M4yK23** [comment]
Hi, I get the same error.I use kibana version 6.3.0
I made the same error I've done the operations you say.

the error I get when I just use timefield and context
I use    
    "%context%":true
   "%timefield%":"date" 
![image](https://user-images.githubusercontent.com/47463408/70319745-181ad880-1834-11ea-9cbf-76af4c716861.png)
I use "%context_query%": "date_depot" ,error
![image](https://user-images.githubusercontent.com/47463408/70319798-3b458800-1834-11ea-8dfd-28e8699e0e18.png)
