### ISSUE TITLE
Vega time histogram x-axis to show hh:mm:ss format-Question

### ISSUE THREAD

**Issue by Sri535** [nyurik/kibana-vega-vis#48]
Hi,
Is there any way to format date field to hh::mm:ss in line graph.
Currently its showing  as ‘Jan 01 2018’
#question

**Comment by nyurik** [comment]
@Sri535 if you use Vega Lite, you can use [config](https://vega.github.io/vega-lite/docs/config.html) to set `timeFormat`, or you could use [axis configurations](https://vega.github.io/vega-lite/docs/axis.html) to set the same thing.  There is also a time unit property you may find useful. If you use Vega, see [axes configuration](https://vega.github.io/vega/docs/axes/).

**Comment by Sri535** [comment]
Thanks #nyurik now i am able to format to time from axis like below
axis:{ title:”time”, format: “%H %M %S”}
