### ISSUE TITLE
Improve plugin installation instructions

### ISSUE THREAD

**Issue by anandgavai** [nyurik/kibana-vega-vis#49]
Example would be sufficient, atleast give an example as to how one should install this plugin in the first place ?

**Comment by nyurik** [comment]
@anandgavai could you suggest how the [two line instruction](https://github.com/nyurik/kibana-vega-vis#quick-demo) could be made clearer? Thx!

**Comment by anandgavai** [comment]
Can you make it clear for example

bin/kibana-plugin install \
   https://github.com/nyurik/kibana-vega-vis/releases/download/<latest_version>.zip

what does <latest_version>.zip mean ? and is it applicable to all versions
of Kibana or elasticsearch.
Can you give an example of <latest_version>.zip. I was not able to install
it on my mac !

**Comment by nyurik** [comment]
Updated. Does that make it clearer?  You are welcome to propose changes.

**Comment by anandgavai** [comment]
Thanks !
It does make it clear as far as installation is concerned, does it depend
on specific version of kibana ?

**Comment by nyurik** [comment]
**Make sure you get the right plugin version that matches your Kibana version, or it won't work!** (from the doc)  -- I thought this was clear that Kibana version must match which download you get.  Please suggest alternative text.

**Comment by anandgavai** [comment]
I was using Kibana 6.2.2 it appears that I will have to downgrade by
version. But its alright.
Thanks !

**Comment by nyurik** [comment]
@anandgavai Kibana 6.2+ has a built-in Vega support. The only limitation is that it doesn't have interactive map base layer support (config / kibana / type=map)

**Comment by anandgavai** [comment]
Alright thanks, what you suggest ? i continue using 6.2.2 ?

**Comment by nyurik** [comment]
@anandgavai unless you need interactive base map (a vega graph that's drawn on top of a map, that can be dragged and zoomed), continue using the latest Kibana & ES. You don't need this plugin.
