### ISSUE TITLE
Auto-size graph

### ISSUE THREAD

**Issue by chuski92** [nyurik/kibana-vega-vis#52]
Hello again @nyurik!
Please, can you help me to discover why is kibana and vega-vis not adjusting the size of the visualization?
Here is what I am viewing:
![vega-vis](https://user-images.githubusercontent.com/33587307/37904158-20544166-30fb-11e8-860d-5e43a4c85bd9.png)
As you can see, a square is showing and not resizing when I minimize the visualization.

Thank you very much!

**Comment by nyurik** [comment]
@chuski92 take a look at the [sizing and positioning section](https://github.com/nyurik/kibana-vega-vis#sizing-and-positioning) in the readme. Your graph has to have the right sizing model, and use width/height signals to calculate proper font sizes and positioning of the elements.

**Comment by chuski92** [comment]
And how can I disable that frame? Can I hide it? It worked to auto-resize, but it is annoying to see that frame in that visualization.

**Comment by nyurik** [comment]
@chuski92 what do you mean by `frame`?  You create the Vega graph, and make that graph dependent on the size of the graph's container. E.g., if the container gets smaller, you reduce the font size, and remove some details.
