### ISSUE TITLE
How can I install vega plugin in Kibana 5.6.1

### ISSUE THREAD

**Issue by Aadil25** [nyurik/kibana-vega-vis#53]
HI Guys,

I am new in Kibana. I want to know that how can I configure vega in Kibana 5.6.1 in ubuntu 16.04.
There is not an option display for vega graphs under Other in Visulization tab in Kibana 5.6.1

Kindly help me to install vega plugin in kibana 5.6.1
I am using elastic search 5.6.1
Kibana 5.6.1

regards,
Adil kadiyawala

**Comment by nyurik** [comment]
You need to follow instructions on the main page with [this older release](https://github.com/nyurik/kibana-vega-vis/releases/tag/v0.5.4). Let me know if you run into problems.
