### ISSUE TITLE
Impossible to tie a search to a vega visual

### ISSUE THREAD

**Issue by thekofimensah** [nyurik/kibana-vega-vis#56]
On vega visual 2.1.4, the search/filter doesn't save with the visual. Impossible to tie a search to a vega visual

To replicate:
Go to vega visual, add a query on the top query box: FIELD:VALUE, save visual. The filter context disappears.

**Comment by nyurik** [comment]
This is the expected behavior. Filters do not save with Vega. Instead, you can create your own query inside the Vega spec, and set any needed filtering there as part of the actual ES query.
If you want your query to also depend on the context, in addition to the query params you specified, you can use things like `%dashboard_context-must_clause%` (see readme).

**Comment by thekofimensah** [comment]
Oh sweet, I didn't see that before, thanks!

**Comment by thekofimensah** [comment]
@nyurik  Are there plans to make it possible for one to either attach the vega to a saved search or attaching a filter/search to it?

**Comment by nyurik** [comment]
@seanziee I'm not sure I understand - what do you mean by attaching vis to a saved search?  Is that a standard Kibana feature? Please elaborate. thx

**Comment by thekofimensah** [comment]
Yes, it is a standard feature. If you go to create a bar chart for example, after clicking on bar chart, you go to a screen that says choose an index or Saved search to use with the visual. That's one way to restrict the data on a visual.

The other way is when you're in the process of creating the visual (like bar chart or most others), there is the standard lucene search bar at the top of the screen that you can send lucene queries for filtering out data for the visual. The Vega visual has that bar, but if you enter a search parameter and save the Vega visual, the search/filter doesn't save with the visual. Does that make sense? You can do it inside the Vega script but it would be nice to also do it with lucene on the top bar (for less technical users who don't want to look at the Vega source).

**Comment by nyurik** [comment]
@seanziee this sounds like an interesting enhancement, but I really want others to look at it too. Could you file this as an enhancement request, with all the details, at https://github.com/elastic/kibana/issues ?  Thx!

**Comment by thekofimensah** [comment]
Just created it [here](https://github.com/elastic/kibana/issues/17709).

:D

**Comment by neosdutertre** [comment]
Where it would still be useful there is a workaround using index aliases:
https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-aliases.html
https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html
