### ISSUE TITLE
Can filters be bi-directional in Vega Vis ?

### ISSUE THREAD

**Issue by sriharshaanp** [nyurik/kibana-vega-vis#63]
Hi, 
I am trying to create a map visualization in Kibana using Vega Vis by overlaying the geographic points on the Kibana default map. I am trying to get the filters in the Kibana dashboard to change based on a selection of a certain object/ point on the map and also affect the other graphs on the dashboard. Can you let me know if this can be done in any way?

Thanks and Regards

**Comment by nyurik** [comment]
This is a work in progress, see https://github.com/elastic/kibana/pull/17586

**Comment by nyurik** [comment]
duplicate of https://github.com/elastic/kibana/issues/17210
