### ISSUE TITLE
Compatibility with Kibana v6.2.4

### ISSUE THREAD

**Issue by dimikhan** [nyurik/kibana-vega-vis#68]
Hi, we are using Kibana v5.5.1 and compatible Vega v0.5.4. Recently we upgraded our dev system to Kibana v6.2.4. We tried to install latest Vega (v1.2.0) for it but it is restricting perhaps because latest Vega is supports till to Kibana v6.2.3.

Even though I tested our custom graph and it still works with Vega v0.5.4 and Kibana v6.2.4; I am wondering if you have any plan to release a compatible version for Kibana v6.2.4 recently. Also, if you can confirm there is backward compatibility of Vega version from Kibana - I mean if old Vega can be used with new Kibana? Thanks

**Comment by nyurik** [comment]
Kibana 6.2 ships with most of the functionality of the plugin built-in, so if all your graphs work ok in 6.2 without the plugin, you should be ok.  The only exception is the "map mode" - showing data on top of an interactive (scrollable & zoomable) map.  I do plan to release newer features for 6.2, but not exactly sure about the schedule.
