### ISSUE TITLE
Unrecognized transform type: "treeify" | Unrecognized transform type: "pivot"

### ISSUE THREAD

**Issue by MD65** [nyurik/kibana-vega-vis#71]
Hello ! 
The transform type "treeify" and  "pivot" don't work on my plateforme vega for KIBANA, what can I do ? 

Thanks.

**Comment by nyurik** [comment]
@MD65 i need more info - are you using plugin or vega that was built into Kibana. What exact version. What Vega spec are you trying that gives you an error.

**Comment by MD65** [comment]
hi @nyurik  ! 

I am using a plugin vega and 6.2.2 for kibana version. 

"$schema": "https://vega.github.io/schema/vega/v3.json",

which is my normal process

![vega_kibana](https://user-images.githubusercontent.com/11718182/40767482-eea59322-64b2-11e8-9cf1-9693623f2340.PNG)

**Comment by MD65** [comment]
"$schema": "https://vega.github.io/schema/vega/v3.json",

**Comment by MD65** [comment]
I have closed this issue by mistake ! Sorry !
