### ISSUE TITLE
How add plugin for vega/kibana ? 

### ISSUE THREAD

**Issue by MD65** [nyurik/kibana-vega-vis#72]
I follow this tuto [https://github.com/nyurik/kibana-vega-vis] but I obtain some error with _npm start._

```
/usr/local/lib/node_modules/npm/bin/npm-cli.js:79
      let notifier = require('update-notifier')({pkg})

```

previously I edited the package.json on the repository /usr/share/kibana/src/core_plugins/vega

**Comment by nyurik** [comment]
@MD65 I'm not sure what issue you are having - vega plugin uses standard Kibana installation.  Could you elaborate what you are trying to do, which versions, etc.

**Comment by MD65** [comment]
I am working on Vega for Kibana 6.2.2 and I can't use some transform type  like "pivot" or Array Functions like "lenght".  `Unrecognized signal name: "lenght"`  I think it is because of a plugin ? right ?

**Comment by nyurik** [comment]
@MD65 `lenght` is spelled [length](https://vega.github.io/vega/docs/expressions/#length). The pivot on the other hand is likely to be missing in the 6.2.2, but should be available if you install the latest plugin from the [releases](https://github.com/nyurik/kibana-vega-vis/releases) page (make sure to get the right version), or if you use Kibana 6.3 which is coming out any day now. Thx!
