### ISSUE TITLE
Click a Tree in VEGA Kibana

### ISSUE THREAD

**Issue by vcaldarelli** [nyurik/kibana-vega-vis#73]
Hello to all.
I created a tree with Vega kibana. Now I would like that when I click a tree node automatically I create a corresponding filter in Kibana and update the tree.
Is this behavior possible?
Thank you.

**Comment by nyurik** [comment]
Sounds like you need the two features that are work in progress - https://github.com/elastic/kibana/pull/17586 and https://github.com/elastic/kibana/pull/17672
feel free to comment on them or on the related issue https://github.com/elastic/kibana/issues/17210
