### ISSUE TITLE
consume API that returns JSON

### ISSUE THREAD

**Issue by MartonEstok** [nyurik/kibana-vega-vis#74]
Hello
is it possible to add an URL that's a public API call returning a JSON when called, instead of an actual JSON file?

So for instance can Vega make a GET to `https://example.org/getData?param=someParam` which'd return a valid JSON file and use that for visualization?

Thanks.

**Comment by nyurik** [comment]
Sure. This is exactly what the URL parameter is for, when it is a string, and not an object
