### ISSUE TITLE
Are the scripts of vega on kibana saved in local ?

### ISSUE THREAD

**Issue by MD65** [nyurik/kibana-vega-vis#76]
I have some problem with my interface kibana, I can't acces it anymore because of the licence x-pack, but all my scripts are in the plateform, it is possible to recuper them from my server  ?

**Comment by nyurik** [comment]
@MD65 I am sorry I don't think I understand.  The Vega graphs are stored the same way as all other visualizations. It is stored in an Elasticsearch, inside a special Kibana index. X-pack should not affect this at all.  Could you try asking this question on [elastic forum](https://discuss.elastic.co/), possibly linking from here?  Thx!

**Comment by MD65** [comment]
@nyurik  Yes, for each visualization there is a script, and you have Answered me that it is stored in an Elasticsearch but  What is the path please on elasticsearch ? I want get back my scripts.

**Comment by nyurik** [comment]
@MD65 I'm not exactly sure about the path - it is using standard storage managed by Kibana itself. Take a look at https://www.elastic.co/guide/en/kibana/current/managing-saved-objects.html -- i think this is what you are looking for.

**Comment by MD65** [comment]
Thank you but it is not what I need ! 
I can anymore acces to my Kibana interface because of my x-pack license expiration, so I would like to know if it is possible to get back all my scripts from my server directly.

**Comment by nyurik** [comment]
@MD65 I consulted with another Kibana dev, and he said
> you can export stuff from the `.kibana` index and the saved visualizations should be in there. But it sounds for me, that you still should be able to access your Kibana, even if your license has expired, by just downgrading it to a basic license again? ... since I think if auth is still in place you would neither be able to access the ES index?

This sounds like a very strange (and bad) situation. Could you post to the ES forum? There should never be a situation when you are locked out of your data, so it sounds like a bigger problem than just Vega itself.

**Comment by MD65** [comment]
Yes it a very  bad situation. I had uninstalled x-pack but this generate other errors, I am actually fixing them.  But for the `.kibana index,` there are a lot, so in wich repository please ?

**Comment by nyurik** [comment]
@MD65 I wish I could help you in depth, but I do not know how exactly Kibana stores this information internally, especially because I do not have access to your data. This is not part of the Vega plugin, it is  how Kibana itself stores all of its visualization data. Please post this question on Elastic forum - Kibana core developers will be able to answer it much better than I can.

**Comment by MD65** [comment]
ok, thanks a lot.
