### ISSUE TITLE
Send Request at same speed of other widget (1s custom)

### ISSUE THREAD

**Issue by toog** [nyurik/kibana-vega-vis#88]
Hello
I made a customization of the time refresh interval to allow Kibana to refresh each second. 
That work for all other widget i put on dashboard except widget Vega. It continue to send each 5 seconds.

Where i can do a trick to enable 1 second refresh for Vega widget ?

**Comment by toog** [comment]
I've found the solution
patching this file : src/core_plugins/vega/public/vega_request_handler.js
with this code : 
`const searchCache = new SearchCache(es, { max: 10, maxAge: 500 });/*old maxAge : 4 * 1000 /
const timeCache = new TimeCache(timefilter, 500);/* old  3 * 1000 */`

and kibana file : /src/ui/public/timepicker/refresh_intervals.js
with adding to function  : `module.constant('refreshIntervals', [`
`{ value: 1000, section: 1 },`

is it possible to integrate this to master ?

**Comment by nyurik** [comment]
This issue was moved to elastic/kibana#31035
