### ISSUE TITLE
Plugin installation was unsuccessful due to error "No valid url specified."

### ISSUE THREAD

**Issue by caopengfei** [nyurik/kibana-vega-vis#90]
./kibana-plugin install /mnt/vega_vis-1.2.0--for-Kibana-6.2.4.zip

Attempting to transfer from /mnt/vega_vis-1.2.0--for-Kibana-6.2.4.zip
Attempting to transfer from https://artifacts.elastic.co/downloads/kibana-plugins//mnt/vega_vis-1.2.0--for-Kibana-6.2.4.zip//mnt/vega_vis-1.2.0--for-Kibana-6.2.4.zip-6.5.1.zip
Plugin installation was unsuccessful due to error "No valid url specified."

**Comment by nyurik** [comment]
Kibana 6.5 already includes this plugin.
