### ISSUE TITLE
Incorrect Kibana version in plugin [vega_vis]. Expected [6.5.1]; found [6.2.4]

### ISSUE THREAD

**Issue by caopengfei** [nyurik/kibana-vega-vis#91]
./kibana-plugin install https://github.com/nyurik/kibana-vega-vis/releases/download/v1.2.0/vega_vis-1.2.0--for-Kibana-6.2.4.zip

response：
Attempting to transfer from https://github.com/nyurik/kibana-vega-vis/releases/download/v1.2.0/vega_vis-1.2.0--for-Kibana-6.2.4.zip
Transferring 9137899 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [vega_vis]. Expected [6.5.1]; found [6.2.4]"

**Comment by nyurik** [comment]
You do not need this plugin for Kibana 6.5, because it already includes it.  Add a visualization and click Vega.
